### ISSUE TITLE
Talk Submission: Write you an Express

### ISSUE THREAD

**Issue by bassjacob** [sydney-node-ninjas/meetup#1]
## Title

Write you an Express
## About

A deep dive from first principles into how Express and similar web-frameworks work under the hood. Start with the bare metal node-http stack and build up something simple from there, explaining how the various pieces work (middleware, router, renderer etc.)
## Duration

Depending on complexity, could go between 30 and 60 mins. 
## Target Audience

Anyone interested in how web servers work under the hood.
## Hardware

Likely will need to step through some code while talking. A podium or something so I can hit the keyboard while standing up would be nice :smile:
## Misc

None :stuck_out_tongue: :

**Comment by jsscclr** [comment]
Hey @bassjacob ! IIRC, I think we said maybe May for this talk? Let me know if this works still- no drama if you're busy :)

**Comment by bassjacob** [comment]
Hey @jsscclr,

I am in fact smashed with getting ready for a conference 😰. Would you mind if we put this off for a month?

**Comment by jsscclr** [comment]
@bassjacob Wooo congrats!!! Absolutely not a problem :) Let me know when you're not swamped and we can sort out when (+ you might not even want to talk about Express anymore :P), no rush ^__^
