### ISSUE TITLE
Talk Submission: TDD and You

### ISSUE THREAD

**Issue by bassjacob** [sydney-node-ninjas/meetup#2]
## Title

TDD and You
## About

The [5W1H](https://en.wikipedia.org/wiki/Five_Ws) about testing. 
- Why to write tests for you application
- How to convince your company that writing tests will save you time and money
- How to structure an application to make writing tests easy
## Duration

30-45 mins
## Target Audience

Beginners and Intermediate
## Hardware

N/A
## Misc

N/A

**Comment by jsscclr** [comment]
Wunderbar! Would you be happy to go ahead with this one next week (October 6)?

**Comment by bassjacob** [comment]
I don't think I have the time to get it ready for next week, but if the Dec one is after I get back from jsconf I can definitely have it ready by then.

**Comment by jsscclr** [comment]
OMG where did I get that date from ?!?!?! No problemo- next meetup we have our December quiz, then skipping January. Sooooooo February?!

**Comment by bassjacob** [comment]
Haha, I guess so. Let's say February :smile:

**Comment by jsscclr** [comment]
Yay! We'll touch base before then though haha :P

**Comment by jsscclr** [comment]
@bassjacob Hey hey! Still happy for next month? It'll be at MI9, near Wynyard (Thursday, February 2) :)

**Comment by bassjacob** [comment]
I think so! Let me double check the date and let you know within a day or two.

**Comment by jsscclr** [comment]
No problemo :)

**Comment by bassjacob** [comment]
This should be fine :smile: I might change the topic slightly away from TDD.

**Comment by jsscclr** [comment]
Thanks so much Jacob, great talk as usual 😄
