### ISSUE TITLE
Talk Submission: Syntactic Sugar for NodeJS Application

### ISSUE THREAD

**Issue by ajainvivek** [sydney-node-ninjas/meetup#3]
## Title

Syntactic Sugar for NodeJS Application
## About

How to use new EcmaScript 2015 (ES6) features in your NodeJS development. 
## Duration

30 - 45 mins talk + 10 mins questions
## Target Audience

Beginners || Intermediate
## Hardware

HDMI port
## Misc

None

**Comment by jsscclr** [comment]
Thanks so much Ajain :D
