### ISSUE TITLE
Talk Submission: Introduction to Jest testing framework

### ISSUE THREAD

**Issue by koresar** [sydney-node-ninjas/meetup#4]
## Title
Introduction to Jest testing framework

## About
[Jest](https://github.com/facebook/jest):
* Install
* Workflow
* Migration from other frameworks
* Neat features

## Duration
From ~15 minutes

## Target Audience
Beginners || Intermediate

## Hardware
HDMI

**Comment by jsscclr** [comment]
Looks great, Vas 😄

**Comment by bassjacob** [comment]
Really looking forward to this :smile:

**Comment by koresar** [comment]
I'm trying to figure out how the approval works.
So, does the Milestone `February @ MI9` mean that my submission was chosen?

**Comment by jsscclr** [comment]
Ooo my bad @koresar, I just assumed James had told you already, but yes! If you're good for next week, that is :)

**Comment by koresar** [comment]
Looks like the talk will take at least 25 minutes, not 15 as I promised.
I hope that's fine.
Nevertheless, I can shorten it on the go if any.

**Comment by jsscclr** [comment]
Great work Vas, loved it!
