### ISSUE TITLE
Talk Submission: Node Ate My Stacktrace

### ISSUE THREAD

**Issue by forkfork** [sydney-node-ninjas/meetup#5]
## Title
Node Ate My Stacktrace

## About
Gotchas, pain, war stories of using Node.js. Why I continue to use it for many things.

## Duration
15-20 minutes

## Target Audience
Intermediate to Advanced

## Hardware
Nothing new!

## Date
Any date should be fine!

## Misc
Potential minor crossover with a previous talk given on optimisation.

**Comment by jsscclr** [comment]
Hey Tim! Sounds great :) Are you cool for May 4th?

**Comment by jsscclr** [comment]
P.S. me following the QR code in your profile pic http://i0.kym-cdn.com/photos/images/newsfeed/000/617/851/56d.gif

**Comment by forkfork** [comment]
I'll say yes and make sure I'm prepared.

I'm the one who made the very unfortunate comment of thinking you were a recruiter.

**Comment by jsscclr** [comment]
Wooo!

To be fair, I *was* surrounded by them!
