### ISSUE TITLE
Talk submission: The Art of Serverlessnessness. 

### ISSUE THREAD

**Issue by tobyhede** [sydney-node-ninjas/meetup#6]
## Title
The Art of Serverlessnessness. 

## About
An intro to node in the clouds with AWS Lambda and serverless

## Duration
10? 20? 
Happy to work in with the other talks.  

## Target Audience
A general overview of Lambda for Beginners
Then dive into using it in the real world for Intermediate || Advanced 

## Hardware
OK

## Date
May 4

## Misc
Lame jokes.

**Comment by jsscclr** [comment]
I can lock you in for next week :D Is 20 minutes okay?

**Comment by tobyhede** [comment]
@jsscclr 20 is good.

**Comment by jsscclr** [comment]
Yay!
