### ISSUE TITLE
Talk Submission: Functional programming in JS

### ISSUE THREAD

**Issue by 0xjocke** [sydney-node-ninjas/meetup#7]
## Title
 Functional programming in JS

## About
I plan to start off by going over some functional patterns that are popular in the javascript community. Examples include pure functions and immutabillty. 

After that I will be taking a deep dive in some patterns that are not popular in javascript but heavily used in functional programming. How we can write our functions in a way that makes it easier to compose them into applications. 

The last part will be about algebraic data types
(ADT) . What they are, how to use them and maybe most importantly, why to use them

## Duration
30 min

## Target Audience
Intermediate || Advanced

## Hardware
Macbook Air, mini display port

## Date
Whenever 

## Misc
Did this talk at CampJS, if you want spoilers: http://fn-presentation.surge.sh/

**Comment by bassjacob** [comment]
Would love to see this, the deck looks great.

**Comment by jsscclr** [comment]
Would love to have you speak :D Does the September meetup work for you?

**Comment by 0xjocke** [comment]
Yes sounds good :)

**Comment by 0xjocke** [comment]
I have some bad news. I'm having some problem with a wisdom tooth and gonna have it taken out on the 6th. Which means that it might be hard to give the talk on the 7th.

Could we postpone my talk to October?

**Comment by jsscclr** [comment]
Sorry, forgot to reply- not a problem, @bachstatter :D

**Comment by jsscclr** [comment]
@bachstatter Hey, you still good for October? Just confirming :)

**Comment by 0xjocke** [comment]
Yes! 😊
