### ISSUE TITLE
Talk Submission: Basics of Cassandra DB for developers

### ISSUE THREAD

**Issue by koresar** [sydney-node-ninjas/meetup#8]
## Title
Basics of Cassandra DB for developers

## About
You will get a good understanding of how data is stored. You are going to learn how to model your Cassandra tables in a performance friendly way. We will run through a real world example. 

## Duration
30-40 minutes. Better be 40 since people usually have questions while I talk.

## Target Audience
Intermediate or Advanced or anyone who knows SQL basics.
The talk is not about DevOpsing. But about development only.

## Hardware
HDMI or USB-C

## Date
Tomorrow 7-th of September, or any future day as needed.

## Misc
That talk was presented at [Alt.Net](https://www.meetup.com/Sydney-Alt-Net/events/240381931/) meetup recently and went really well. Although, it has nothing node.js related (except one slide with JS examples).
But since node.js is about web performance and Cassandra is about backend performance I thought it can be useful.
Of course I'll insert plethora of jokes throughout the talk as usual. :)

**Comment by rprieto** [comment]
Thanks Vasyl, it sounds great! Looking forward to your talk tomorrow, and it's now official: http://www.nodesydney.com/pages/next-event.html

**Comment by koresar** [comment]
You have the website now! Wow

**Comment by rprieto** [comment]
Yes we're announcing that tomorrow. You can say you were the first person to see it :smile:
